// Profile.js

import Head from "next/head";
import SideBar from "@/app/components/SideBar";
import Card from "@/app/components/Cards"; // Ensure this path is correct

const Profile = ({ params }) => {
  const username = params.username;

  return (
    <div className="flex h-screen">
      <Head>
        <title>Modern Card</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <div className="w-1/6">
        <SideBar />
      </div>
      <div className="flex-grow flex justify-center items-center p-4">
        <Card username={username} />
      </div>
    </div>
  );
};

export default Profile;
